sudo: requires
services:
  - docker

language: python
python:
  - "2.7"

install:
  - pip install flake8
  - sudo apt-get update -qq
  - sudo apt-get install -y luarocks
  - sudo luarocks install luacheck
  - docker pull bamos/openface

script:
  - flake8 --ignore=E402,E501 .
  - luacheck . --no-global --no-self --exclude-files '*/torch-TripletEmbedding'
  - |
    docker run -v $PWD:/root/src/openface bamos/openface \
           /bin/bash -l -c "cd /root/src/openface; \
                            ./models/get-models.sh && \
                            python2 setup.py install && \
                            nosetests-2.7 -v -d test.py"
